version: "3.9"

volumes: 
  web_data:
  db_data:

services:
  psql:
    image: postgres
    restart: always
    env_file:
      - ./db/.env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data/
  
  web:
    build: .
    volumes:
      - web_data:/code
    command: 
      python mysite/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - psql
    

networks:
  django-network:
    name: django-network