version: "3.9"

volumes: 
  web_data:

services:
  web:
    build: .
    volumes:
      - web_data:/code

  web_migrate:
    extends:
      service: web
    command:
      python mysite/manage.py migrate

  web_run:
    extends:
      service: web
    command: 
      python mysite/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"