version: '3.8'
services:
  psql-db:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
      - ./polls.sql:/docker-entrypoint-initdb.d/create_tables.sql
